### ISSUE TITLE
Undefined 'd3_document'

### ISSUE THREAD

**Issue by joesavage** [mbostock/d3#2245]
After having recently updated some dependencies in a Node.js project of mine, I'm now finding that d3 isn't working correctly. The following JavaScript, for example, works great for me under Node v0.10.25 with d3 version 3.4.11 but fails with the error  `TypeError: Cannot read property 'querySelector' of undefined [at d3_select]` under Node v0.12.0 with d3 version 3.5.5.

 ```
var d3 = require('d3');
var chart = d3.select("body").append("div");
 ```

I can't tell if this is just a change in behaviour between the d3 versions that I haven't noticed or is something else, but it's certainly frustrating.

**Comment by jasondavies** [comment]
See [this comment](https://github.com/mbostock/d3/pull/2225#issuecomment-73426201) for a suggested fix.  This is happening due to a change in the way JSDOM is supported, and removal of the runtime dependency on a global `document`, as of version [3.5.4](https://github.com/mbostock/d3/releases/tag/v3.5.4).

**Comment by alex88** [comment]
Is there a fix for node.js? JSDOM works only on io.js

**Comment by jasondavies** [comment]
You can still use JSDOM 3.x with Node.js.

**Comment by alex88** [comment]
Ok found that, thanks a lot!

**Comment by raees** [comment]
I noted that with JSDOM 3.x still there are some problems and it show me errors:

TypeError: e:\htdocs\hiwi\d3serverside\index.html:28
   26|   <body>
   27|     <h1>D3 Server-side Demo</h1>
>> 28|     <%=
   29|       barChartHelper.getBarChart({
   30|         data: fixtureData,
   31|         width: 400,

Cannot read property 'querySelector' of undefined
   at d3_select (e:\htdocs\hiwi\d3serverside\node_modules\d3\d3.js:562:13)
   at Object.d3.select (e:\htdocs\hiwi\d3serverside\node_modules\d3\d3.js:1043:17)
   at Object.getBarChart (e:\htdocs\hiwi\d3serverside\bar_chart_helper.js:15:6)
   at eval (eval at <anonymous> (e:\htdocs\hiwi\d3serverside\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:31:22)
   at eval (eval at <anonymous> (e:\htdocs\hiwi\d3serverside\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:48:38)
   at e:\htdocs\hiwi\d3serverside\node_modules\ejs\lib\ejs.js:255:15
   at Object.exports.render (e:\htdocs\hiwi\d3serverside\node_modules\ejs\lib\ejs.js:293:13)
   at View.exports.renderFile [as engine] (e:\htdocs\hiwi\d3serverside\node_modules\ejs\lib\ejs.js:323:20)
   at View.render (e:\htdocs\hiwi\d3serverside\node_modules\express\lib\view.js:76:8)
   at Function.app.render (e:\htdocs\hiwi\d3serverside\node_modules\express\lib\application.js:496:10)
