### ISSUE TITLE
TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by miguelmota** [mbostock/d3#2502]
```bash
$ iojs app.js
TypeError: Cannot read property 'document' of undefined
    at /Users/moogs/Development/app/node_modules/d3/d3.js:8:25
    at Object.<anonymous> (/Users/moogs/Development/app/node_modules/d3/d3.js:9504:2)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.cls_wrapMethod (/Users/moogs/Development/app/node_modules/newrelic/li
b/shimmer.js:230:38)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/moogs/Development/app/node_modules/d3/index.js:6:18
)

$ iojs --version
v2.4.0
```

`app.js`

```javascript
let d3 = require('d3');
```

**Comment by mbostock** [comment]
I tried your app.js, and it gave me the following error:

```
$ iojs app.js 
/Users/mbostock/…/app.js:1
(function (exports, require, module, __filename, __dirname) { let d3 = require
                                                              ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:471:10)
    at startup (node.js:117:18)
    at node.js:948:3
```

I am guessing that you have `iojs` aliased to `iojs --use_strict`, which reproduces your error. But this requires ALL require’d JavaScript to also be in strict mode, not just code that opts in using `"use strict"`. So… don’t do that.

Strict mode is currently unsupported; D3 needs to work in a wide variety of environments and it uses `this.document` to check if the global document exists. We could use `typeof document === "undefined"` instead, but we still need a way to set the global `d3`. And that’s difficult to do in strict mode while supporting all these environments.

**Comment by miguelmota** [comment]
Yes my mistake, I was using strict mode and harmony flag. Makes sense. Thanks for the insight!

**Comment by Buroni** [comment]
Is this worth revisiting now that ES modules are more widespread? d3 doesn't work inside ES modules, which are always in strict mode.

**Comment by fillipeags** [comment]
Any news on that ? Im trying to migrate a project to vite but i'm unable to make the app work because one of my project libs uses d3 in it's dependency list
